Se arrelaron algunos comentarios
EnzoSives/Veterinaria pull request #6
Opened 2022-08-11 20:48 UTC by EnzoSives

2022-08-12 18:12 UTC, SofiZ2001 requested changes

2022-08-12 18:12 UTC, SofiZ2001 commented on Veterinaria/cliente.ts
>     private id: number;
el id lo debería heredar del padre

2022-08-12 18:12 UTC, SofiZ2001 commented on Veterinaria/persona.ts
> +    private telefono: number;
Deberían estar todas como protected asi pueden heredarse por los hijos

2022-08-12 18:12 UTC, SofiZ2001 commented on Veterinaria/veterinaria.ts
>          this.clientes.push(cliente);
Cuando se da de alta un cliente hay que implementar la funcionalidad de que no tengan el mismo id, sino se debera generar uno nuevo (Pueden utilizar el `Math.random()` para generar numeros aleatorios)

2022-08-12 18:12 UTC, SofiZ2001 commented on Veterinaria/veterinaria.ts
> +    modificarPaciente(paciente:Paciente){}
Funcion vacía, hay que implementarla

2022-08-12 18:12 UTC, SofiZ2001 commented on Veterinaria/paciente.ts
> +    getEsVip() {
La clase cliente (sería dueño del paciente) es el que se encarga de saber si es un cliente VIP o no

2022-08-12 18:12 UTC, SofiZ2001 commented on Veterinaria/paciente.ts
> +    private visita: number;
el cliente es el que debería tener la cantidad de veces que visito la veterinaria. Ademas el Paciente lleva un id, que es el mismo id del dueño

2022-08-29 21:37 UTC, EnzoSives commented on Veterinaria/veterinaria.ts
>          this.clientes.push(cliente);
altaCliente(cliente:Cliente): void {
        for (let i = 0; i < this.clientes.length; i++) {
            if(this.clientes[i] === cliente)
            this.clientes.push(cliente);
            this.id = Math.floor((Math.random() * 100) + 1);       
  }}
Puede ser que asi este bien la funcion?

2022-08-31 20:01 UTC, SofiZ2001 commented on Veterinaria/veterinaria.ts
>          this.clientes.push(cliente);
Para qué estaría ese if? 
Va por ahi la idea con el Math.floor pero deben asegurarse que ese numero random generado no sea uno ya existente. 
Pueden probar algo asi:
```
let id = 0
                while(id == 0){
                    id = Math.floor(Math.random()* 100)

                    if(this.clientes.find(cliente => cliente.getId() == id)){ // "find" automaticamente recorre toda la lista en busca de coincidencias. Si encuentra alguna coincidencia retorna true, si no false
                        id = 0 // Si ya existe ese id, se le vuelve a setear 0 y asi puede entrar en el while devuelta para generar uno nuevo.
                    } else {
                        this.clientes.push(cliente) //Si no lo encuentra entre los ids existentes, quiere decir que puede guardarse. 
                        cliente.setId(id) // le seteamos el id que generamos al nuevo cliente y sale del while, porque la variable id ya no es 0
                    }
                }
```

Chusmeenlo a ver que les parece, si ven algo que no entienden o no les cierra me preguntan y lo vemos!

2022-08-31 20:15 UTC, SofiZ2001 requested changes
dos pequeños comments pero ya casi! 👍🏼

2022-08-31 20:15 UTC, SofiZ2001 commented on Veterinaria/veterinaria.ts
> +            this.id = Math.floor((Math.random() * 100) + 1);
Probá haciendo las modificaciones que te hice en el comment donde me preguntaste :D

2022-08-31 20:15 UTC, SofiZ2001 commented on Veterinaria/veterinaria.ts
> +        return  this.id = Math.floor((Math.random() * 100) + 1);
Este generarId lo tenemos que utilizar para los clientes (en este caso) cuando los tenemos que agregar, con el this estamos llamando al id de nuestra clase, o sea la veterinaria.
En todo caso podrías retornar directamente el `Math.floor(...)` y eso ya te retorna un numero aleatorio. Esta funcion podes utilizarla dentro del altaCliente cuando necesitas generar el id del cliente

2022-09-01 22:12 UTC, SofiZ2001 requested changes
Otros mini comments

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/cliente.ts
> +   protected id:number;
`protected` sería si en algun caso los hijos de la clase Cliente tuvieran que acceder directamente al atributo id.
En este caso Cliente no tiene hijos y no es necesario, podemos setearlo tranquilamente como `private`
Recorda que para acceder/modificar atributos de una clase en otra tenemos los `getters/setters`

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/paciente.ts
> +    public edad:number;
No usemos los atributos en `public`, estaban bien como `private`
Si necesitas acceder a ellos los podes hacer mediante los getters, por ejemplo

```
p = new Paciente(...)
p.getNombre() // un metodo get que retorna el nombre
```

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/persona.ts
> +    public telefono: number;
Revisar el comment anterior sobre el modificador de acceso `public`

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/proveedor.ts
> +    protected id : number;
No es necesario que sea protected

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/redVeterinaria.ts
> +        this.veterinarias.push(veterinaria);
Las veterinarias tambien llevan un id, hay que replicar lo mismo que con Clientes. Se le debe setear un id random autogenerado y unico

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/redVeterinaria.ts
> +            this.proveedor[i] = ReadlineSync.question('ingrese datos de nuevo proveedor');
La funcionalidad de modificar primero tiene que: 

- Encontrar el proveedor que se quiere modificar en el arreglo
- Si lo encuentra, ese proveedor se le van a modificar sus atributos (hacer el uso de los setters)
Ej:
`proveedor[i].setNombre(ReadlineSync.question("Ingresar el nuevo nombre del proveedor: ")`

2022-09-01 22:12 UTC, SofiZ2001 commented on Veterinaria/redVeterinaria.ts
> +    modificarVeterinaria(veterinaria: Veterinaria, nuevaVeterinaria: string) {
Replicar lo mismo de modificar proveedor en esta funcion

2022-09-07 12:45 UTC, SofiZ2001 requested changes
2 mini comments!

2022-09-07 12:45 UTC, SofiZ2001 commented on Veterinaria/veterinaria.ts
> +        let id:number = 0;
Los pacientes llevan el id del dueño (`Cliente`) por lo tanto no es necesario generar un id random.
Tip: Pueden hacer que esta funcion reciba al dueño (de tipo `Cliente`) como parametro. Asi pueden obtener el id del mismo y asignarselo al paciente con un setter

2022-09-07 12:45 UTC, SofiZ2001 commented on Veterinaria/redVeterinaria.ts
> +            if(proveedor[i]=== nuevoProveedor){
El parametro proveedor lo veo innecesario. solamente recibiría  un proveedor que es el que queremos modificar.
Dentro del if hay que llamar a la lista, `proveedores[i]` para hacer la comparacion.
Luego el tema del  === es que al comparar dos Objects siempre va a tirar false porque no compara por contenido (aunque tengan exactamente lo mismo) sino por el espacio asignado en memoria)
Recomiendo que lo hagan preguntando si tienen el mismo id
(Replicarlo en todos los metodos de modificar que tengan)

2022-09-07 19:40 UTC, SofiZ2001 approved these changes
LG2M

2022-09-07 19:40 UTC, merged